---
- name: Check for Broadcom Driver (bnxt_en)
  shell: /usr/sbin/lsmod | grep bnxt_en
  ignore_errors: true
  register: has_broadcom_driver

- name: Disable offload for ens3
  shell: "/usr/sbin/ethtool -K ens3 tx off"
  when: has_broadcom_driver

- name: Add Kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no

- name: Install YUM packages (RHEL/CentOS)
  yum:
    name: "{{ pkgs }}"
    update_cache: yes

- name: Disable system swap
  shell: "swapoff -a"

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Disable selinux (ephemeral)
  shell: setenforce 0

- name: Disable selinux (persistent)
  selinux:
    state: disabled

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable swappiness and pass bridged IPv4 traffic to iptable chains
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.swappiness', value: '0' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }

- name: Copy kubeadm conf to drop-in directory
  template: src=20-extra-args.conf.j2 dest=/etc/systemd/system/kubelet.service.d/20-extra-args.conf

- name: Reload kubelet daemon
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
