---
- name: Reset kubeadm0
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
      kubeadm join {{ groups['master'][0] }}:6443 \
        --token {{ kubeadm.token }} \
        --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['master'][0]]["discovery-token-ca-cert-hash"].stdout }}
  register: join_cluster

- name: Enable and restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
