---
- name: Apply OCI Volume Provisioner config
  shell:
    cmd: |
      cat <<EOF | kubectl apply --kubeconfig=/etc/kubernetes/admin.conf -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: oci-volume-provisioner
        namespace: kube-system
      data:
        config.yaml: {{ lookup('template', './config.yaml.j2') | b64encode }}
      EOF

- name: Apply OCI Flexvolume Driver RBAC
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
    https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/flexvolume-driver/oci-flexvolume-driver-rbac.yaml

- name: Apply OCI Flexvolume driver
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
    https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/flexvolume-driver/oci-flexvolume-driver.yaml

- name: Apply OCI Volume Provisioner RBAC
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
    https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/volume-provisioner/oci-volume-provisioner-rbac.yaml

- name: Apply OCI Block Volume Provisioner
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
    https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/volume-provisioner/oci-volume-provisioner.yaml

- name: Apply OCI FSS Volume Provisioner
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
    https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/volume-provisioner/oci-volume-provisioner-fss.yaml

- name: Create default OCI StorageClass
  shell:
    cmd: |
      cat <<EOF | kubectl apply --kubeconfig=/etc/kubernetes/admin.conf -f -
      kind: StorageClass
      apiVersion: storage.k8s.io/v1beta1
      metadata:
        name: oci
      provisioner: oracle.com/oci
      EOF


