---
- name: Apply OCI Cloud Controller Manager config
  shell:
    cmd: |
      cat <<EOF | kubectl apply --kubeconfig=/etc/kubernetes/admin.conf -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: oci-cloud-controller-manager
        namespace: kube-system
      data:
        cloud-provider.yaml: {{ lookup('template', './cloud-provider-config.yaml.j2') | b64encode }}
      EOF

- name: Apply OCI Cloud Controller Manager RBAC
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
    https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/cloud-controller-manager/oci-cloud-controller-manager-rbac.yaml

- name: Apply OCI Cloud Controller Manager DaemonSet
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \
    https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/master/manifests/cloud-controller-manager/oci-cloud-controller-manager.yaml
